# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai911displaychatdisplay_pb2 as ai911displaychatdisplay__pb2


class Ai911DispatcherChatDisplayStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishMessage = channel.unary_unary(
                '/ai911displaychatdisplay.Ai911DispatcherChatDisplay/PublishMessage',
                request_serializer=ai911displaychatdisplay__pb2.PublishMessageRequest.SerializeToString,
                response_deserializer=ai911displaychatdisplay__pb2.PublishMessageResponse.FromString,
                )


class Ai911DispatcherChatDisplayServicer(object):
    """Service definition
    """

    def PublishMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Ai911DispatcherChatDisplayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishMessage,
                    request_deserializer=ai911displaychatdisplay__pb2.PublishMessageRequest.FromString,
                    response_serializer=ai911displaychatdisplay__pb2.PublishMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai911displaychatdisplay.Ai911DispatcherChatDisplay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ai911DispatcherChatDisplay(object):
    """Service definition
    """

    @staticmethod
    def PublishMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai911displaychatdisplay.Ai911DispatcherChatDisplay/PublishMessage',
            ai911displaychatdisplay__pb2.PublishMessageRequest.SerializeToString,
            ai911displaychatdisplay__pb2.PublishMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
