# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai911displaychatdisplay.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ai911displaychatdisplay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61i911displaychatdisplay.proto\x12\x17\x61i911displaychatdisplay\"E\n\x15PublishMessageRequest\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\"&\n\x16PublishMessageResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t2\x8f\x01\n\x1a\x41i911DispatcherChatDisplay\x12q\n\x0ePublishMessage\x12..ai911displaychatdisplay.PublishMessageRequest\x1a/.ai911displaychatdisplay.PublishMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai911displaychatdisplay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_start=58
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_end=127
  _globals['_PUBLISHMESSAGERESPONSE']._serialized_start=129
  _globals['_PUBLISHMESSAGERESPONSE']._serialized_end=167
  _globals['_AI911DISPATCHERCHATDISPLAY']._serialized_start=170
  _globals['_AI911DISPATCHERCHATDISPLAY']._serialized_end=313
# @@protoc_insertion_point(module_scope)
