# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai911dispatcher_pb2 as ai911dispatcher__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai911dispatcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MainServiceStub(object):
    """Define the Address message
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateSession = channel.unary_unary(
                '/ai911dispatcher.MainService/InitiateSession',
                request_serializer=ai911dispatcher__pb2.User.SerializeToString,
                response_deserializer=ai911dispatcher__pb2.SuccessCode.FromString,
                _registered_method=True)
        self.SendCallerResponse = channel.unary_unary(
                '/ai911dispatcher.MainService/SendCallerResponse',
                request_serializer=ai911dispatcher__pb2.CallerResponse.SerializeToString,
                response_deserializer=ai911dispatcher__pb2.SuccessCode.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/ai911dispatcher.MainService/EndSession',
                request_serializer=ai911dispatcher__pb2.User.SerializeToString,
                response_deserializer=ai911dispatcher__pb2.SuccessCode.FromString,
                _registered_method=True)


class MainServiceServicer(object):
    """Define the Address message
    """

    def InitiateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCallerResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateSession,
                    request_deserializer=ai911dispatcher__pb2.User.FromString,
                    response_serializer=ai911dispatcher__pb2.SuccessCode.SerializeToString,
            ),
            'SendCallerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCallerResponse,
                    request_deserializer=ai911dispatcher__pb2.CallerResponse.FromString,
                    response_serializer=ai911dispatcher__pb2.SuccessCode.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=ai911dispatcher__pb2.User.FromString,
                    response_serializer=ai911dispatcher__pb2.SuccessCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai911dispatcher.MainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai911dispatcher.MainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MainService(object):
    """Define the Address message
    """

    @staticmethod
    def InitiateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai911dispatcher.MainService/InitiateSession',
            ai911dispatcher__pb2.User.SerializeToString,
            ai911dispatcher__pb2.SuccessCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCallerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai911dispatcher.MainService/SendCallerResponse',
            ai911dispatcher__pb2.CallerResponse.SerializeToString,
            ai911dispatcher__pb2.SuccessCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai911dispatcher.MainService/EndSession',
            ai911dispatcher__pb2.User.SerializeToString,
            ai911dispatcher__pb2.SuccessCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
