# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai911dispatcher.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ai911dispatcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61i911dispatcher.proto\x12\x0f\x61i911dispatcher\"\x18\n\x04User\x12\x10\n\x08phoneNum\x18\x01 \x01(\t\"\x1d\n\x0bSuccessCode\x12\x0e\n\x06status\x18\x01 \x01(\t\"\"\n\x0e\x43\x61llerResponse\x12\x10\n\x08Response\x18\x01 \x01(\t2\xed\x01\n\x0bMainService\x12\x46\n\x0fInitiateSession\x12\x15.ai911dispatcher.User\x1a\x1c.ai911dispatcher.SuccessCode\x12S\n\x12SendCallerResponse\x12\x1f.ai911dispatcher.CallerResponse\x1a\x1c.ai911dispatcher.SuccessCode\x12\x41\n\nEndSession\x12\x15.ai911dispatcher.User\x1a\x1c.ai911dispatcher.SuccessCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai911dispatcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=42
  _globals['_USER']._serialized_end=66
  _globals['_SUCCESSCODE']._serialized_start=68
  _globals['_SUCCESSCODE']._serialized_end=97
  _globals['_CALLERRESPONSE']._serialized_start=99
  _globals['_CALLERRESPONSE']._serialized_end=133
  _globals['_MAINSERVICE']._serialized_start=136
  _globals['_MAINSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
